# Generated by Django 6.0.4 on 2026-07-21 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_picture'),
        ('accounts', '0002_user_specialization'),
    ]

    operations = [
    ]
