# Generated by Django 6.0.4 on 2026-07-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0004_studentattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='explanation',
            field=models.TextField(blank=True, help_text='Explanation for the correct answer.', null=True),
        ),
    ]
