# Generated by Django 6.0.4 on 2026-07-15 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_enrollment_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicsession',
            options={'ordering': ['-start_year']},
        ),
        migrations.AddField(
            model_name='academicsession',
            name='end_year',
            field=models.PositiveIntegerField(default=2025),
        ),
        migrations.AddField(
            model_name='academicsession',
            name='start_year',
            field=models.PositiveIntegerField(default=2024),
        ),
        migrations.RemoveField(
            model_name='batch',
            name='admission_year',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='status',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='session',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='credit',
        ),
        migrations.AddField(
            model_name='batch',
            name='academic_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.academicsession'),
        ),
        migrations.AddField(
            model_name='batch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='current_semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_enrollments', to='academics.semester'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('THEORY', 'Theory'), ('PRACTICAL', 'Practical'), ('ELECTIVE', 'Elective')], default='THEORY', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='academicsession',
            unique_together={('start_year', 'end_year')},
        ),
        migrations.RemoveField(
            model_name='academicsession',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='academicsession',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='academicsession',
            name='name',
        ),
        migrations.RemoveField(
            model_name='academicsession',
            name='start_date',
        ),
    ]
