# Generated by Django 6.0.4 on 2026-07-15 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_academicsession_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='name',
        ),
        migrations.AlterField(
            model_name='batch',
            name='academic_session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academics.academicsession'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='number',
            field=models.CharField(max_length=20),
        ),
    ]
