# Generated by Django 6.0.4 on 2026-07-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_remove_batch_name_alter_batch_academic_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Date after which the batch is considered inactive.', null=True),
        ),
    ]
