# Generated by Django 6.0.4 on 2026-07-19 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_batch_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='academic_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='academics.academicsession'),
        ),
    ]
