# Generated by Django 6.0.4 on 2026-07-20 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(upload_to='alumni_stories/')),
                ('current_role', models.CharField(help_text='e.g., Wildlife Researcher, PhD Scholar', max_length=255)),
                ('testimonial', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=True, help_text='Show this story on the landing page.')),
                ('student', models.OneToOneField(help_text='Select a student from an inactive/graduated batch.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Alumni Stories',
                'ordering': ['-created_at'],
            },
        ),
    ]
