# Generated by Django 5.0.7 on 2024-07-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alumnistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnistory',
            name='student',
        ),
        migrations.AddField(
            model_name='alumnistory',
            name='batch_year',
            field=models.PositiveIntegerField(default=2020, help_text='Year of graduation (e.g., 2019)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumnistory',
            name='student_name',
            field=models.CharField(default='Default Name', max_length=200),
            preserve_default=False,
        ),
    ]