# Generated by Django 6.0.4 on 2026-07-19 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreeDModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, help_text='Optional preview image.', null=True, upload_to='3d_thumbnails/')),
                ('model_file_glb', models.FileField(blank=True, help_text='Viewer file (.glb format recommended)', null=True, upload_to='3d_models/glb/')),
                ('model_file_gltf', models.FileField(blank=True, help_text='Converted .gltf format', null=True, upload_to='3d_models/gltf/')),
                ('model_file_usdz', models.FileField(blank=True, help_text='Converted .usdz format (for AR on Apple devices)', null=True, upload_to='3d_models/usdz/')),
                ('model_file_fbx', models.FileField(blank=True, help_text='Original .fbx format', null=True, upload_to='3d_models/fbx/')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
